
// To check if a library is compiled with CocoaPods you
// can use the `COCOAPODS` macro definition which is
// defined in the xcconfigs so it is available in
// headers also when they are imported in the client
// project.


// CTAssetsPickerController
#define COCOAPODS_POD_AVAILABLE_CTAssetsPickerController
#define COCOAPODS_VERSION_MAJOR_CTAssetsPickerController 2
#define COCOAPODS_VERSION_MINOR_CTAssetsPickerController 3
#define COCOAPODS_VERSION_PATCH_CTAssetsPickerController 1

// MRProgress
#define COCOAPODS_POD_AVAILABLE_MRProgress
#define COCOAPODS_VERSION_MAJOR_MRProgress 0
#define COCOAPODS_VERSION_MINOR_MRProgress 7
#define COCOAPODS_VERSION_PATCH_MRProgress 0

// MRProgress/ActivityIndicator
#define COCOAPODS_POD_AVAILABLE_MRProgress_ActivityIndicator
#define COCOAPODS_VERSION_MAJOR_MRProgress_ActivityIndicator 0
#define COCOAPODS_VERSION_MINOR_MRProgress_ActivityIndicator 7
#define COCOAPODS_VERSION_PATCH_MRProgress_ActivityIndicator 0

// MRProgress/Blur
#define COCOAPODS_POD_AVAILABLE_MRProgress_Blur
#define COCOAPODS_VERSION_MAJOR_MRProgress_Blur 0
#define COCOAPODS_VERSION_MINOR_MRProgress_Blur 7
#define COCOAPODS_VERSION_PATCH_MRProgress_Blur 0

// MRProgress/Circular
#define COCOAPODS_POD_AVAILABLE_MRProgress_Circular
#define COCOAPODS_VERSION_MAJOR_MRProgress_Circular 0
#define COCOAPODS_VERSION_MINOR_MRProgress_Circular 7
#define COCOAPODS_VERSION_PATCH_MRProgress_Circular 0

// MRProgress/Helper
#define COCOAPODS_POD_AVAILABLE_MRProgress_Helper
#define COCOAPODS_VERSION_MAJOR_MRProgress_Helper 0
#define COCOAPODS_VERSION_MINOR_MRProgress_Helper 7
#define COCOAPODS_VERSION_PATCH_MRProgress_Helper 0

// MRProgress/Icons
#define COCOAPODS_POD_AVAILABLE_MRProgress_Icons
#define COCOAPODS_VERSION_MAJOR_MRProgress_Icons 0
#define COCOAPODS_VERSION_MINOR_MRProgress_Icons 7
#define COCOAPODS_VERSION_PATCH_MRProgress_Icons 0

// MRProgress/NavigationBarProgress
#define COCOAPODS_POD_AVAILABLE_MRProgress_NavigationBarProgress
#define COCOAPODS_VERSION_MAJOR_MRProgress_NavigationBarProgress 0
#define COCOAPODS_VERSION_MINOR_MRProgress_NavigationBarProgress 7
#define COCOAPODS_VERSION_PATCH_MRProgress_NavigationBarProgress 0

// MRProgress/Overlay
#define COCOAPODS_POD_AVAILABLE_MRProgress_Overlay
#define COCOAPODS_VERSION_MAJOR_MRProgress_Overlay 0
#define COCOAPODS_VERSION_MINOR_MRProgress_Overlay 7
#define COCOAPODS_VERSION_PATCH_MRProgress_Overlay 0

// MRProgress/ProgressBaseClass
#define COCOAPODS_POD_AVAILABLE_MRProgress_ProgressBaseClass
#define COCOAPODS_VERSION_MAJOR_MRProgress_ProgressBaseClass 0
#define COCOAPODS_VERSION_MINOR_MRProgress_ProgressBaseClass 7
#define COCOAPODS_VERSION_PATCH_MRProgress_ProgressBaseClass 0

// MRProgress/Stopable
#define COCOAPODS_POD_AVAILABLE_MRProgress_Stopable
#define COCOAPODS_VERSION_MAJOR_MRProgress_Stopable 0
#define COCOAPODS_VERSION_MINOR_MRProgress_Stopable 7
#define COCOAPODS_VERSION_PATCH_MRProgress_Stopable 0

